package protocol

const (
	ActionPing              = "ping"
	ActionVersion           = "version"
	ActionAccountInfo       = "account_info"
	ActionTerminalInfo      = "terminal_info"
	ActionSymbolsTotal      = "symbols_total"
	ActionSymbolsGet        = "symbols_get"
	ActionSymbolInfo        = "symbol_info"
	ActionSymbolInfoTick    = "symbol_info_tick"
	ActionSymbolSelect      = "symbol_select"
	ActionCopyRatesFrom     = "copy_rates_from"
	ActionCopyRatesFromPos  = "copy_rates_from_pos"
	ActionCopyRatesRange    = "copy_rates_range"
	ActionCopyTicksFrom     = "copy_ticks_from"
	ActionCopyTicksRange    = "copy_ticks_range"
	ActionMarketBookAdd     = "market_book_add"
	ActionMarketBookGet     = "market_book_get"
	ActionMarketBookRelease = "market_book_release"
	ActionOrderSend         = "order_send"
	ActionOrderCheck        = "order_check"
	ActionOrderCalcMargin   = "order_calc_margin"
	ActionOrderCalcProfit   = "order_calc_profit"
	ActionOrdersTotal       = "orders_total"
	ActionOrdersGet         = "orders_get"
	ActionPositionsTotal    = "positions_total"
	ActionPositionsGet      = "positions_get"
	ActionHistoryOrdersTotal = "history_orders_total"
	ActionHistoryOrdersGet   = "history_orders_get"
	ActionHistoryDealsTotal  = "history_deals_total"
	ActionHistoryDealsGet    = "history_deals_get"
	ActionSubscribeTicks     = "subscribe_ticks"
	ActionUnsubscribeTicks   = "unsubscribe_ticks"
)
