name: chart

on:
  schedule:
    - cron: "37 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: chart

jobs:
  chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: Mukbeast4/star-candles@main
